import type { SeedCategory } from "./seed";

export const hamaratBusiness = {
  id: "biz_hamarat",
  name: "Hamarat Pastane & Kafe",
  slug: "hamarat",
  subtitle: "Pastane • Kafe • Fast Food",
};

export const hamaratCategories: SeedCategory[] = [
  {
    id: "hamarat_cat_fast_food",
    name: "Fast Food",
    imageUrl: "/images/hamarat-fast-food.png",
    items: [
      { name: "Hamburger", price: 135, weight: "1 adet", kcal: 480, allergens: ["gluten", "milk", "eggs", "sesame"] },
      { name: "Hamarat Burger", price: 165, weight: "1 adet", kcal: 650, allergens: ["gluten", "milk", "eggs", "sesame", "mustard"] },
      { name: "Patso", price: 105, weight: "1 adet", kcal: 520, allergens: ["gluten", "milk", "eggs"] },
      { name: "Karışık Tost", price: 115, weight: "1 adet", kcal: 520, allergens: ["gluten", "milk"] },
      { name: "Peynirli Tost", price: 90, weight: "1 adet", kcal: 400, allergens: ["gluten", "milk"] },
      { name: "Sandviç", price: 95, weight: "1 adet", kcal: 380, allergens: ["gluten", "milk", "eggs"] },
    ],
  },
  {
    id: "hamarat_cat_unlu_mamuller",
    name: "Unlu Mamüller",
    imageUrl: "/images/hamarat-unlu-mamuller.png",
    items: [
      { name: "Simit", price: 25, weight: "1 adet", kcal: 330, allergens: ["gluten", "sesame"] },
      { name: "Poğaça", price: 35, weight: "1 adet", kcal: 300, allergens: ["gluten", "milk", "eggs"] },
      { name: "Açma", price: 35, weight: "1 adet", kcal: 350, allergens: ["gluten", "milk", "eggs"] },
      { name: "Gül Böreği", price: 70, weight: "1 porsiyon", kcal: 390, allergens: ["gluten", "milk", "eggs"] },
      { name: "Kol Böreği", price: 85, weight: "1 porsiyon", kcal: 430, allergens: ["gluten", "milk", "eggs"] },
      { name: "Su Böreği", price: 95, weight: "1 porsiyon", kcal: 450, allergens: ["gluten", "milk", "eggs"] },
      { name: "Kapalı Pizza", price: 75, weight: "1 adet", kcal: 500, allergens: ["gluten", "milk"] },
      { name: "Mini Pizza", price: 55, weight: "1 adet", kcal: 220, allergens: ["gluten", "milk"] },
      {
        name: "Kurabiye Çeşitleri",
        price: 80,
        weight: "1 adet / ~50 g",
        kcal: 230,
        allergens: ["gluten", "milk", "eggs", "nuts"],
        allergenNote: "Çeşide göre sert kabuklu yemiş içerebilir.",
      },
    ],
  },
  {
    id: "hamarat_cat_yas_pasta",
    name: "Yaş Pasta",
    imageUrl: "/images/hamarat-yas-pasta.png",
    items: [
      { name: "Yaş Pasta 01", price: 145, weight: "1 dilim", kcal: 360, allergens: ["gluten", "milk", "eggs"] },
      { name: "Yaş Pasta 02", price: 150, weight: "1 dilim", kcal: 390, allergens: ["gluten", "milk", "eggs"] },
      { name: "Yaş Pasta 03", price: 155, weight: "1 dilim", kcal: 410, allergens: ["gluten", "milk", "eggs"] },
      { name: "Baton Yaş Pasta", price: 450, weight: "1 dilim", kcal: 380, allergens: ["gluten", "milk", "eggs"] },
      { name: "Mini Baton Yaş Pasta", price: 250, weight: "1 adet", kcal: 520, allergens: ["gluten", "milk", "eggs"] },
      {
        name: "Mozaik Pasta",
        price: 110,
        weight: "1 dilim",
        kcal: 420,
        allergens: ["gluten", "milk", "nuts"],
        allergenNote: "Çeşide göre fındık içerebilir.",
      },
    ],
  },
  {
    id: "hamarat_cat_adet_pasta",
    name: "Adet Pasta",
    imageUrl: "/images/hamarat-yas-pasta.png",
    items: [
      { name: "Köstebek Pasta Mini", price: 95, weight: "1 adet", kcal: 330, allergens: ["gluten", "milk", "eggs"] },
      { name: "Ekler Mini", price: 85, weight: "1 adet", kcal: 170, allergens: ["gluten", "milk", "eggs"] },
      { name: "Muffin", price: 80, weight: "1 adet", kcal: 380, allergens: ["gluten", "milk", "eggs"] },
      {
        name: "Magnolia",
        price: 125,
        weight: "1 porsiyon",
        kcal: 430,
        allergens: ["milk", "gluten", "nuts"],
        allergenNote: "Çeşide göre fındık içerebilir.",
      },
      { name: "Profiterol", price: 115, weight: "1 porsiyon", kcal: 480, allergens: ["gluten", "milk", "eggs"] },
      { name: "Supangle", price: 110, weight: "1 porsiyon", kcal: 330, allergens: ["milk", "gluten"] },
      { name: "Cheesecake", price: 145, weight: "1 dilim", kcal: 450, allergens: ["gluten", "milk", "eggs"] },
      {
        name: "Malaga",
        price: 150,
        weight: "1 adet",
        kcal: 430,
        allergens: ["gluten", "milk", "eggs", "nuts"],
        allergenNote: "Çeşide göre fındık içerebilir.",
      },
    ],
  },
  {
    id: "hamarat_cat_tatlilar",
    name: "Tatlılar",
    imageUrl: "/images/hamarat-tatlilar.png",
    items: [
      {
        name: "Fındıklı ve Cevizli Baklava",
        price: 170,
        weight: "1 porsiyon / ~100 g",
        kcal: 520,
        allergens: ["gluten", "milk", "nuts"],
        allergenNote: "Fındık ve ceviz içerir.",
      },
      {
        name: "Soğuk Baklava",
        price: 160,
        weight: "1 porsiyon / ~100 g",
        kcal: 470,
        allergens: ["gluten", "milk", "nuts"],
        allergenNote: "Antep fıstığı veya diğer sert kabuklu yemişler içerebilir.",
      },
      {
        name: "Burma Kadayıf",
        price: 150,
        weight: "1 porsiyon / ~100 g",
        kcal: 500,
        allergens: ["gluten", "milk", "nuts"],
        allergenNote: "Antep fıstığı veya ceviz içerebilir.",
      },
      { name: "Laz Böreği", price: 125, weight: "1 porsiyon", kcal: 420, allergens: ["gluten", "milk", "eggs"] },
      { name: "Revani", price: 90, weight: "1 dilim", kcal: 330, allergens: ["gluten", "milk", "eggs"] },
      { name: "Şekerpare", price: 90, weight: "2 adet", kcal: 360, allergens: ["gluten", "milk", "eggs"] },
      { name: "Sütlaç", price: 100, weight: "1 kase", kcal: 280, allergens: ["milk"] },
      { name: "Kazandibi", price: 105, weight: "1 porsiyon", kcal: 300, allergens: ["milk"] },
    ],
  },
  {
    id: "hamarat_cat_sicak_icecekler",
    name: "Sıcak İçecekler",
    imageUrl: "/images/hamarat-sicak-icecekler.png",
    items: [
      { name: "Küçük Çay", price: 30, weight: "şekersiz", kcal: 2, allergens: [] },
      { name: "Fincan Çay", price: 40, weight: "şekersiz", kcal: 2, allergens: [] },
      { name: "Türk Kahvesi", price: 80, weight: "şekersiz", kcal: 7, allergens: [] },
      { name: "Nescafe", price: 75, weight: "sade", kcal: 5, allergens: [] },
      { name: "Filtre Kahve", price: 90, weight: "sade", kcal: 5, allergens: [] },
      { name: "Sütlü Filtre Kahve", price: 105, weight: "1 fincan", kcal: 90, allergens: ["milk"] },
      { name: "Latte", price: 110, weight: "~300 ml", kcal: 170, allergens: ["milk"] },
      {
        name: "Sıcak Çikolata",
        price: 95,
        weight: "~300 ml",
        kcal: 250,
        allergens: ["milk", "soy"],
        allergenNote: "Ürüne göre soya içerebilir.",
      },
      { name: "Sahlep", price: 95, weight: "~250 ml", kcal: 220, allergens: ["milk"] },
    ],
  },
  {
    id: "hamarat_cat_soguk_icecekler",
    name: "Soğuk İçecekler",
    imageUrl: "/images/hamarat-soguk-icecekler.jpg",
    items: [
      { name: "Su", price: 25, weight: "1 şişe", kcal: 0, allergens: [] },
      { name: "Soda", price: 35, weight: "1 şişe", kcal: 0, allergens: [] },
      { name: "Meyveli Soda", price: 45, weight: "1 şişe", kcal: 70, allergens: [] },
      {
        name: "Şişe İçecek",
        price: 65,
        weight: "~330 ml",
        kcal: 140,
        allergens: [],
        allergenNote: "Alerjen bilgisi ürüne göre değişebilir.",
      },
      { name: "Limonata", price: 75, weight: "~300 ml", kcal: 150, allergens: [] },
      {
        name: "Hamarat Şerbeti",
        price: 80,
        weight: "~300 ml",
        kcal: 180,
        allergens: ["nuts"],
        allergenNote: "Reçeteye göre sert kabuklu yemiş içerebilir.",
      },
      { name: "Küçük Meyve Suyu", price: 40, weight: "~200 ml", kcal: 90, allergens: [] },
    ],
  },
];
