import type { AllergenKey } from "@/types/menu";

export type NutritionInfo = {
  kcal: number;
  allergens: AllergenKey[];
};

const nutritionEntries: Array<[string, string, number, AllergenKey[]]> = [
  ["Çorbalar", "Kellepaça", 430, []],
  ["Çorbalar", "İşkembe (Kazan)", 320, []],
  ["Çorbalar", "Tuzlama", 350, []],
  ["Çorbalar", "Damar Tuzlama", 380, []],
  ["Çorbalar", "Dana Ayak Paça Kemiksiz", 440, []],
  ["Çorbalar", "Kuzu Ayak Paça Kemikli", 420, []],
  ["Çorbalar", "Antep Usulü Beyran", 480, []],
  ["Çorbalar", "Şazende Karışık Special", 520, []],
  ["Çorbalar", "Beyin Söğüş", 360, []],
  ["Çorbalar", "Yarım Tandır Kelle", 600, []],
  ["Çorbalar", "Tam Tandır Kelle", 1150, []],
  ["Çorbalar", "Dil Söğüş", 400, []],
  ["Çorbalar", "Çürük", 430, []],
  ["Çorbalar", "Dil Paça", 450, []],
  ["Çorbalar", "Munbar Dolması", 620, ["gluten"]],
  ["Çorbalar", "Tavuk Suyu", 190, ["gluten"]],
  ["Çorbalar", "Mercimek", 240, ["gluten"]],
  ["Çorbalar", "Tereyağlı Mercimek", 290, ["gluten", "milk"]],
  ["Çorbalar", "Ezogelin", 250, ["gluten"]],
  ["Sulu Yemekler", "Kuru Fasülye", 430, []],
  ["Sulu Yemekler", "Taze Fasülye", 280, []],
  ["Sulu Yemekler", "Patlıcan Musakka", 470, []],
  ["Sulu Yemekler", "Karnıyarık", 500, []],
  ["Sulu Yemekler", "İzmir Köfte", 560, ["gluten"]],
  ["Sulu Yemekler", "Arnavut Ciğeri", 520, ["gluten"]],
  ["Sulu Yemekler", "Tas Kebabı", 470, []],
  ["Sulu Yemekler", "Fırın Köfte", 520, ["gluten"]],
  ["Sulu Yemekler", "Çoban Kavurma", 650, []],
  ["Sulu Yemekler", "Tavuk Sote", 430, []],
  ["Sulu Yemekler", "Tavuk Haşlama", 360, []],
  ["Sulu Yemekler", "Ispanak", 260, []],
  ["Sulu Yemekler", "Karnabahar", 250, []],
  ["Sulu Yemekler", "Pırasa", 270, []],
  ["Sulu Yemekler", "Pirinç Pilavı", 330, ["milk"]],
  ["Sulu Yemekler", "Bulgur Pilavı", 300, ["gluten"]],
  ["Izgaralar", "Adana", 720, []],
  ["Izgaralar", "Urfa", 690, []],
  ["Izgaralar", "Tavuk Şiş", 610, []],
  ["Izgaralar", "Kanat", 780, []],
  ["Izgaralar", "Et Şiş", 680, []],
  ["Izgaralar", "Karışık Izgara", 1250, []],
  ["Dürümler", "Adana Dürüm", 650, ["gluten"]],
  ["Dürümler", "Urfa Dürüm", 620, ["gluten"]],
  ["Dürümler", "Ciğer Şiş Dürüm", 600, ["gluten"]],
  ["Dürümler", "Tavuk Şiş Dürüm", 520, ["gluten"]],
  ["Dürümler", "Et Şiş Dürüm", 610, ["gluten"]],
  ["Dürümler", "Köfte Dürüm", 620, ["gluten"]],
  ["Tavuk Dönerler", "Yarım Ekmek", 430, ["gluten"]],
  ["Tavuk Dönerler", "Tombik", 420, ["gluten"]],
  ["Tavuk Dönerler", "Porsiyon", 500, []],
  ["Tavuk Dönerler", "Pilavüstü", 720, ["milk"]],
  ["Tavuk Dönerler", "Dürüm", 500, ["gluten"]],
  ["Tavuk Dönerler", "3 Çeyrek", 540, ["gluten"]],
  ["Tavuk Dönerler", "Bütün Ekmek", 720, ["gluten"]],
  ["Et Dönerler", "Yarım Ekmek Et Döner", 520, ["gluten"]],
  ["Et Dönerler", "Tombik Et Döner", 510, ["gluten"]],
  ["Et Dönerler", "Porsiyon Et Döner", 560, []],
  ["Et Dönerler", "Pilavüstü Et Döner", 790, ["milk"]],
  ["Et Dönerler", "Dürüm Et Döner", 590, ["gluten"]],
  ["Et Dönerler", "3 Çeyrek Et Döner", 630, ["gluten"]],
  ["Et Dönerler", "Beyti", 880, ["gluten", "milk"]],
  ["Et Dönerler", "Tereyağlı İskender", 950, ["gluten", "milk"]],
  ["Et Dönerler", "Tam Ekmek Et Döner", 790, ["gluten"]],
  ["Fırınlar", "Lahmacun", 360, ["gluten"]],
  ["Fırınlar", "Kaşarlı Lahmacun", 440, ["gluten", "milk"]],
  ["Fırınlar", "Fındık Lahmacun", 180, ["gluten"]],
  ["Fırınlar", "B. Boy Kaşarlı Pide", 850, ["gluten", "milk"]],
  ["Fırınlar", "B. Boy Kıymalı Pide", 900, ["gluten"]],
  ["Fırınlar", "Sucuklu Pide", 950, ["gluten"]],
  ["Fırınlar", "Sucuklu Kaşarlı Pide", 1080, ["gluten", "milk"]],
  ["Fırınlar", "Kuşbaşılı Pide", 900, ["gluten"]],
  ["Fırınlar", "Kavurmalı Pide", 1000, ["gluten"]],
  ["Fırınlar", "Karışık Pide", 1050, ["gluten", "milk"]],
  ["Fırınlar", "Şazende Pizza", 1050, ["gluten", "milk"]],
  ["Salatalar", "Çoban Salata", 150, []],
  ["Salatalar", "Cacık", 140, ["milk"]],
  ["Salatalar", "Ezme", 130, []],
  ["Salatalar", "Yoğurt", 170, ["milk"]],
  ["Salatalar", "Roka Salatası", 140, []],
  ["Salatalar", "Roka", 40, []],
  ["Salatalar", "Mevsim Salata", 150, []],
  ["Salatalar", "Haydari", 220, ["milk"]],
  ["Salatalar", "Adana Salatası", 140, []],
  ["Tatlılar", "Sütlaç", 330, ["milk"]],
  ["Tatlılar", "Künefe", 650, ["gluten", "milk"]],
  ["Tatlılar", "Kemalpaşa", 420, ["gluten", "milk"]],
  ["Tatlılar", "Zerde", 250, []],
  ["İçecekler", "Su", 0, []],
  ["İçecekler", "Soda", 0, []],
  ["İçecekler", "Şalgam", 30, []],
  ["İçecekler", "Küçük Ayran", 70, ["milk"]],
  ["İçecekler", "Büyük Ayran", 120, ["milk"]],
  ["İçecekler", "Sarıyer Kola Litrelik", 420, []],
  ["İçecekler", "Kutu Sarıyer", 140, []],
];

export const nutritionByCategoryAndName = new Map(
  nutritionEntries.map(([category, name, kcal, allergens]) => [
    `${category}|${name}`,
    { kcal, allergens },
  ]),
);

export function getNutritionInfo(categoryName: string, itemName: string) {
  return nutritionByCategoryAndName.get(`${categoryName}|${itemName}`) ?? null;
}
