create table if not exists public.pos_tables (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  area text not null default 'Salon',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (business_id, name)
);

create table if not exists public.pos_orders (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  table_id uuid references public.pos_tables(id) on delete set null,
  order_no bigint generated by default as identity,
  source text not null default 'table' check (source in ('table', 'counter')),
  status text not null default 'open' check (status in ('open', 'paid', 'cancelled', 'refunded')),
  note text,
  total_amount numeric(10,2) not null default 0,
  payment_summary text,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.pos_orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  name_snapshot text not null,
  unit_price numeric(10,2) not null default 0,
  quantity integer not null default 1 check (quantity > 0),
  line_total numeric(10,2) generated always as (unit_price * quantity) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, menu_item_id)
);

create table if not exists public.pos_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.pos_orders(id) on delete cascade,
  method text not null check (method in ('cash', 'card')),
  amount numeric(10,2) not null check (amount >= 0),
  paid_at timestamptz not null default now()
);

create table if not exists public.pos_settings (
  business_id uuid primary key references public.businesses(id) on delete cascade,
  report_pin_hash text not null,
  report_lock_minutes integer not null default 3,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pos_tables_business_order
on public.pos_tables(business_id, sort_order);

create index if not exists idx_pos_orders_business_status
on public.pos_orders(business_id, status, opened_at desc);

create index if not exists idx_pos_orders_table_open
on public.pos_orders(table_id)
where status = 'open';

create index if not exists idx_pos_order_items_order
on public.pos_order_items(order_id);

create index if not exists idx_pos_payments_order
on public.pos_payments(order_id);

alter table public.pos_tables enable row level security;
alter table public.pos_orders enable row level security;
alter table public.pos_order_items enable row level security;
alter table public.pos_payments enable row level security;
alter table public.pos_settings enable row level security;

drop policy if exists "POS can read tables" on public.pos_tables;
create policy "POS can read tables"
on public.pos_tables for select
to anon, authenticated
using (true);

drop policy if exists "POS can manage tables" on public.pos_tables;
create policy "POS can manage tables"
on public.pos_tables for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "POS can read orders" on public.pos_orders;
create policy "POS can read orders"
on public.pos_orders for select
to anon, authenticated
using (true);

drop policy if exists "POS can manage orders" on public.pos_orders;
create policy "POS can manage orders"
on public.pos_orders for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "POS can read order items" on public.pos_order_items;
create policy "POS can read order items"
on public.pos_order_items for select
to anon, authenticated
using (true);

drop policy if exists "POS can manage order items" on public.pos_order_items;
create policy "POS can manage order items"
on public.pos_order_items for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "POS can read payments" on public.pos_payments;
create policy "POS can read payments"
on public.pos_payments for select
to anon, authenticated
using (true);

drop policy if exists "POS can manage payments" on public.pos_payments;
create policy "POS can manage payments"
on public.pos_payments for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "POS can read settings" on public.pos_settings;
create policy "POS can read settings"
on public.pos_settings for select
to anon, authenticated
using (true);

drop policy if exists "POS can manage settings" on public.pos_settings;
create policy "POS can manage settings"
on public.pos_settings for all
to anon, authenticated
using (true)
with check (true);

with business as (
  select id from public.businesses where slug = 'hamarat'
),
table_seed(name, area, sort_order) as (
  values
    ('Masa 1', 'İÇERİ', 10),
    ('Masa 2', 'İÇERİ', 20),
    ('Masa 3', 'İÇERİ', 30),
    ('Masa 4', 'İÇERİ', 40),
    ('Masa 5', 'İÇERİ', 50),
    ('Masa 6', 'İÇERİ', 60),
    ('Masa 7', 'DIŞARI', 110),
    ('Masa 8', 'DIŞARI', 120),
    ('Masa 9', 'DIŞARI', 130),
    ('Masa 10', 'DIŞARI', 140),
    ('Masa 11', 'DIŞARI', 150)
)
insert into public.pos_tables (business_id, name, area, sort_order)
select business.id, table_seed.name, table_seed.area, table_seed.sort_order
from business
cross join table_seed
on conflict (business_id, name) do update
set area = excluded.area,
    sort_order = excluded.sort_order,
    is_active = true;

with business as (
  select id from public.businesses where slug = 'hamarat'
)
insert into public.pos_settings (business_id, report_pin_hash, report_lock_minutes)
select id, 'db117cadaeb576c942833bb254fc33154d23dc2db268fd2541401dbe2fb6be96', 3
from business
on conflict (business_id) do update
set report_pin_hash = excluded.report_pin_hash,
    report_lock_minutes = excluded.report_lock_minutes,
    updated_at = now();
